server:
  port: 8000
web.upload-path: E:/img
spring:
  application:
    name: demo1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://101.200.48.168:3306/pm?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: Hamikeji123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    filters: stat
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/public/,file:${web.upload-path}
eureka:
  client:
        registerWithEureka: false
        fetchRegistry: false

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
mybatis:
  mapper-locations=classpath: com/example/demo1/v1/mapping/mapper
  type-aliases-package: com.example.demo1.v1
